/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    { type: 'html', value: '<a class="navbar__brand custom-top-header" href="/"><div class="navbar__logo"><img src="/img/social/favicon-64x64.png" alt="Vesuvius Challenge Logo" class="themedImage_ToTc themedImage--dark_i4oU"></div><b class="navbar__title text--truncate">Vesuvius Challenge</b></a>' },
    {
      type: 'category',
      label: 'Overview',
      link: { type: 'doc', id: 'landing' },
      items: [
        { type: 'doc', id: 'get_started' },
        { type: 'doc', id: 'master_plan' },
      ]
    },
    {
      type: 'category',
      label: 'Competition',
      link: { type: 'doc', id: '28_2024_prizes' },
      items: [
        { type: 'doc', id: '28_2024_prizes' },
        { type: 'doc', id: 'winners' },
        { type: 'doc', id: 'community_projects' },
      ],
    },
    {
      type: 'category',
      label: 'Data',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'data' },
      items: [
        { type: 'doc', id: 'data_scrolls' },
        { type: 'doc', id: 'data_fragments' },
        { type: 'doc', id: 'data_segments' },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'tutorial1' },
      items: [
        { type: 'doc', id: 'tutorial1' },
        { type: 'doc', id: 'tutorial2' },
        { type: 'doc', id: 'tutorial3' },
        { type: 'doc', id: 'tutorial4' },
        { type: 'doc', id: 'tutorial5' },
      ],
    },
    { type: 'doc', id: 'faq' },
    { type: 'doc', id: 'livestream' },
    {
      type: 'link',
      label: 'Discord',
      href: 'https://discord.gg/V4fJhvtaQn',
    },
    {
      type: 'link',
      label: 'Blog',
      href: 'https://scrollprize.substack.com/',
    },
    {
      type: 'link',
      label: 'X',
      href: 'https://x.com/scrollprize',
    },
  ],
};

module.exports = sidebars;
